# This is a basic workflow to help you get started with Actions

name: Deploy ADF

on:
  push:
    branches: [ main ]
    paths:
      - adf/
      - *.json
  pull_request:
    branches: [ main ]
      - adf/
      - *.json
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - name: Validate ADF Template in Repo
        run: npm run build validate ./adf ${{ secrets.DEV_ADF_RESOURCE_ID }}

      - name: Export ADF Template in Repo
        run: npm run build export ./adf ${{ secrets.DEV_ADF_RESOURCE_ID }} "ArmTemplates"

      - uses: actions/upload-artifact@v3
        with:
          name: adf-arm-template
          path: ./ArmTemplates

  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: adf-arm-template

    - name: Validate working directory contents
      run: ls -R -l ./

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.NONPRD_AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.DEV_AZURE_KEY_VAULT }}
        secrets: 'data-lake-service-url'
      id: getAKVSecret

    - name: Run Pre Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.DEV_AZURE_RG }} -DataFactoryName ${{ secrets.DEV_FACTORY_NAME }} -predeployment $true -deleteDeployment $false
        azPSVersion: "latest"
      
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.NONPRD_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.DEV_AZURE_RG }}
        template: ./ARMTemplateForFactory.json
        parameters: ./parameters.qa.json factoryName=${{ secrets.DEV_FACTORY_NAME }} AzureDataLakeStorage1_properties_typeProperties_url=${{ steps.getAKVSecret.outputs.data-lake-service-url }} AzureKeyVault1_properties_typeProperties_baseUrl=${{ secrets.DEV_AZURE_KEY_VAULT }}
  
    - name: Run Post Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.DEV_AZURE_RG }} -DataFactoryName ${{ secrets.DEV_FACTORY_NAME }} -predeployment $false -deleteDeployment $true
        azPSVersion: "latest"

    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: adf-arm-template

    - name: Validate working directory contents
      run: ls -R -l ./

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.NONPRD_AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.QA_AZURE_KEY_VAULT }}
        secrets: 'data-lake-service-url'
      id: getAKVSecret

    - name: Run Pre Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.QA_AZURE_RG }} -DataFactoryName ${{ secrets.QA_FACTORY_NAME }} -predeployment $true -deleteDeployment $false
        azPSVersion: "latest"

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.NONPRD_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.NONPRD_AZURE_RG }}
        template: ./ARMTemplateForFactory.json
        parameters: ./parameters.qa.json factoryName=${{ secrets.QA_FACTORY_NAME }} AzureDataLakeStorage1_properties_typeProperties_url=${{ steps.getAKVSecret.outputs.data-lake-service-url }} AzureKeyVault1_properties_typeProperties_baseUrl=${{ secrets.QA_AZURE_KEY_VAULT }}

    - name: Run Post Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.QA_AZURE_RG }} -DataFactoryName ${{ secrets.QA_FACTORY_NAME }} -predeployment $false -deleteDeployment $true
        azPSVersion: "latest"
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: adf-arm-template

    - name: Validate working directory contents
      run: ls -R -l ./

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.PRD_AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.PRD_AZURE_KEY_VAULT }}
        secrets: 'data-lake-service-url'
      id: getAKVSecret

    - name: Run Pre Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.PRD_AZURE_RG }} -DataFactoryName ${{ secrets.PRD_FACTORY_NAME }} -predeployment $true -deleteDeployment $false
        azPSVersion: "latest"
      
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.PRD_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.PRD_AZURE_RG }}
        template: ./ARMTemplateForFactory.json
        parameters: ./parameters.prd.json factoryName=${{ secrets.PRD_FACTORY_NAME }} AzureDataLakeStorage1_properties_typeProperties_url=${{ steps.getAKVSecret.outputs.data-lake-service-url }} AzureKeyVault1_properties_typeProperties_baseUrl=${{ secrets.PRD_AZURE_KEY_VAULT }}

    - name: Run Post Deploy Script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./adf-pre-post-deploy.ps1 -armTemplate "./ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.PRD_AZURE_RG }} -DataFactoryName ${{ secrets.PRD_FACTORY_NAME }} -predeployment $false -deleteDeployment $true
        azPSVersion: "latest"

